import type { SxProps, Theme } from '@mui/material'
import { C } from '../../theme/theme'

export const navbarStyles: Record<string, SxProps<Theme>> = {
  appBar: {
    bgcolor: 'transparent',
    boxShadow: 'none',
    borderBottom: '1px solid transparent',
    transition: 'background-color .35s ease, box-shadow .35s ease, backdrop-filter .35s ease, border-color .35s ease',
    '&.scrolled': {
      bgcolor: `${C.cream}E0`,
      backdropFilter: 'saturate(140%) blur(12px)',
      WebkitBackdropFilter: 'saturate(140%) blur(12px)',
      borderBottomColor: `${C.lavender200}80`,
      boxShadow: '0 1px 0 rgba(255,255,255,0.6) inset',
    },
  },
  toolbar: {
    maxWidth: 1280,
    width: '100%',
    mx: 'auto',
    px: { xs: 2.5, md: 4 },
    justifyContent: 'space-between',
    minHeight: { xs: 64, md: 72 },
  },
  brandBox: {
    display: 'flex',
    alignItems: 'center',
    gap: 1.5,
    cursor: 'pointer',
    textDecoration: 'none',
  },
  brandText: {
    fontFamily: '"Cormorant Garamond", serif',
    fontStyle: 'italic',
    fontSize: { xs: 17, md: 19 },
    lineHeight: 1.05,
    color: C.purple800,
    fontWeight: 500,
  },
  brandSub: {
    display: 'block',
    fontSize: 12,
    color: C.gold700,
    fontStyle: 'normal',
    letterSpacing: '0.02em',
    fontFamily: '"Inter", sans-serif',
  },
  desktopNav: {
    display: 'flex',
    gap: { md: 0.5, lg: 1 },
    alignItems: 'center',
  },
  navButton: {
    fontSize: 14,
    fontWeight: 500,
    color: C.purple800,
    px: 1.5,
    py: 0.75,
    borderRadius: '6px',
    position: 'relative',
    '&::after': {
      content: '""',
      position: 'absolute',
      left: 12, right: 12, bottom: 4,
      height: '1px',
      background: C.gold500,
      transform: 'scaleX(0)',
      transformOrigin: 'left',
      transition: 'transform .25s ease',
    },
    '&:hover::after': { transform: 'scaleX(1)' },
    '&:hover': { bgcolor: 'transparent', color: C.purple800 },
  },
  registerButton: {
    ml: 1.5,
    fontWeight: 600,
    boxShadow: `0 4px 14px rgba(42,85,66,0.28)`,
    '&:hover': { transform: 'translateY(-1px)', boxShadow: `0 8px 22px rgba(42,85,66,0.36)` },
  },
  drawerBox: {
    width: 'min(360px, 86vw)',
    pt: 1,
    background: C.cream,
    height: '100%',
  },
  drawerLink: {
    padding: '14px 12px',
    borderRadius: '10px',
    fontSize: 16,
    fontWeight: 500,
    color: C.purple800,
    '&:hover': { background: C.lavender50 },
  },
  iconColor: {
    color: C.purple800,
  },
}
